Severity Code Description Project File Line Suppression State Error CS7069 Reference to type 'IBusControl' claims it is defined in 'MassTransit', but it could not be found MyRest.Booking C:\My_Study_Csh\Quarter4\MDA\MyRest\Restaurant.Booking\Program.cs 51 Active